image: registry.gitlab.com/zurnaz/serverless-python-gitlab-ci

stages:
  - build
  - test
  - deploy
  - e2e tests
  - release
  # - release tests

variables:
  dev: 'dev-$CI_COMMIT_REF_SLUG'
  # Artifact from other repo settings
  OUT_FILE: input-stack.json
  REF: master
  BASE_URL: https://gitlab.com
  PROJECT: 13697110 # project id of serverless stateful gitlab ci
  PER_PAGE: 50

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - venv/

install python:
  stage: build
  script:
    - python3 -m venv  venv
    - source venv/bin/activate
    - pip3 install -r dev-requirements.txt
    - pip3 install -r requirements.txt

install js:
  stage: build
  script:
    - yarn install --frozen-lockfile

lint javascript:
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn lint

lint python:
  stage: test
  script:
    - source venv/bin/activate
    - pylint src

unit tests python:
  stage: test
  script:
    - source venv/bin/activate
    - pytest tests

dev:
  stage: deploy
  variables:
    STAGE: dev
  script:
    - curl -sL https://gitlab.com/morph027/gitlab-ci-helpers/raw/master/get-last-successful-build-artifact.sh
    - sls deploy -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    on_stop: stop_dev
  artifacts:
    untracked: false
    paths:
      - stack.json
    expire_in: 4 days

e2e tests dev:
  stage: e2e tests
  script:
    - source venv/bin/activate
    - pytest e2e
  except:
    - master
  dependencies:
    - dev

staging:
  stage: deploy
  variables:
    STAGE: staging # target stage of artifact from other repo
  script:
    - curl -sL https://gitlab.com/morph027/gitlab-ci-helpers/raw/master/get-last-successful-build-artifact.sh
    - ls
    - sls deploy -s staging -v
  environment:
    name: staging
    on_stop: stop_staging
  only:
    - master
  artifacts:
    untracked: false
    paths:
      - stack.json

e2e tests staging:
  stage: e2e tests
  script:
    - ls # TODO REMOVE:: For testing is the stack.json is there
    - source venv/bin/activate
    - pytest e2e
  only:
    - master
  dependencies:
    - staging

deploy live:
  stage: release
  variables:
    STAGE: live
  script:
    - . <(curl -sL https://gitlab.com/morph027/gitlab-ci-helpers/raw/master/get-last-successful-build-artifact.sh)
    - sls deploy -s live -v
  environment:
    name: live
  only:
    - master
  when: manual

stop_dev:
  stage: deploy
  script:
    - sls remove -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    action: stop
  when: delayed
  start_in: 24 hour

stop_staging:
  stage: deploy
  script:
    - sls remove -s staging -v
  environment:
    name: staging
    action: stop
  when: manual
