image: registry.gitlab.com/zurnaz/serverless-gitlab-ci-example

stages:
  - build
  - test
  - deploy
  - e2e tests
  - release
  # - release tests

variables:
  dev: 'dev-$CI_COMMIT_REF_SLUG'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - venv/

install js:
  stage: build
  image: node:slim # Needs python for a sepecific package TODO update docker image
  script:
    - yarn install --frozen-lockfile

install python:
  stage: build
  image: python:3.7-stretch
  script:
    - python3 -m venv  venv
    - source venv/bin/activate
    - pip3 install -r dev-requirements.txt
    - pip3 install -r requirements.txt

lint javascript:
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn lint

lint python:
  stage: test
  image: python:3.7-stretch
  script:
    - source venv/bin/activate
    - pylint src

unit tests python:
  stage: test
  image: python:3.7-stretch
  script:
    - source venv/bin/activate
    - pytest tests

dev:
  stage: deploy
  script:
    - sls deploy -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    on_stop: stop_dev
  artifacts:
    untracked: false
    paths:
      - stack.json
    expire_in: 4 days

e2e tests dev:
  stage: e2e tests
  image: python:3.7-stretch
  script:
    - pytest e2e
  except:
    - master
  dependencies:
    - dev

staging:
  stage: deploy
  script:
    - sls deploy -s staging -v
  environment:
    name: staging
    on_stop: stop_staging
  only:
    - master
  artifacts:
    untracked: false
    paths:
      - stack.json

e2e tests staging:
  stage: e2e tests
  image: python:3.7-stretch
  script:
    - pytest e2e
  only:
    - master
  dependencies:
    - staging

deploy live:
  stage: release
  script:
    - sls deploy -s live -v
  environment:
    name: live
  only:
    - master
  when: manual

stop_dev:
  stage: deploy
  script:
    - sls remove -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    action: stop
  when: delayed
  start_in: 24 hour

stop_staging:
  stage: deploy
  script:
    - sls remove -s staging -v
  environment:
    name: staging
    action: stop
  when: manual
